""" Implementation of the user agent client hints according to:
    https://github.com/WICG/ua-client-hints
"""

from .constants import CPUBitness
from typing import TypedDict

""" Output dictionary """
class ClientHints(TypedDict, total = True):
    Sec_CH_UA                   : str
    Sec_CH_UA_Arch              : str
    Sec_CH_UA_Bitness           : str
    Sec_CH_UA_Full_Version_List : str
    Sec_CH_UA_Mobile            : str
    Sec_CH_UA_Model             : str
    Sec_CH_UA_Platform          : str
    Sec_CH_UA_Platform_Version  : str


# Generic string formatter for the hints
format = lambda x: f'"{x}"' if x else '""'


def ClientHintGenerator(browser: dict, cpu: dict, device: dict, os: dict) -> dict:
    """ Generates client hints from a parsed user agent. 
        Inputs are the dicts generated by the user agent scraper.
        See: ./ua_scraper/scraper.py
    """

    d = {
        'UA_Platform_Version'  : _UAGeneric(os.get('version')),
        'UA_Full_Version_List' : _UA(browser.get('name'), browser.get('version'), fullVersion = True),
        'UA_Platform'          : _UAPlatform(os.get('name')),
        'UA_Bitness'           : _UABitness(cpu.get('architecture')),
        'UA_Mobile'            : _UAMobile(device.get('type')),
        'UA_Model'             : _UAGeneric(device.get('model')),
        'UA_Arch'              : _UAGeneric(cpu.get('architecture')),
        'UA'                   : _UA(browser.get('name'), browser.get('majorVersion'))
        }

    return d
    

def _UABitness(
    name     : str, # CPU architecture
    cpuToBit : dict = CPUBitness,
    ) -> str:
    """ Generates the value of the Sec-CH-UA-Bitness header.
        See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Bitness
    """
    
    return format(cpuToBit.get(name))


def _UAGeneric(
    architecture: str # CPU architecutre
    ) -> str:
    """ Generates the value of the Sec-CH-UA-Arch, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version headers.
        See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Arch
             https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Model
             https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Platform-Version
    """

    return format(architecture)


def _UAMobile(
    s: str # Device type
    ) -> str:
    """ Generates the value of the Sec-CH-UA-Mobile header.
        See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Mobile
    """
        
    if s == 'mobile':
        return '?1'
    else:
        return '?0'
    

def _UAPlatform(
    name # Name of the operating system
    ) -> str:
    """ Generates the value of the Sec-CH-UA-Platform header.
        See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Platform
    """
    
    if name is not None and name.lower() not in ['ios', 'mac os']: 
        name = name.title()

    return format(name)


def _UA(
    name    : str, # Browser name
    version : str,  # Major (Significant) version of the browser
    fullVersion: bool = False
    ) -> str: 
    """ Generates the value of the Sec-CH-UA and Sec-CH-UA-Full-Version-List headers.
        See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA
        and  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Full-Version-List
    """

    # Intentionally incorrect brand string
    if fullVersion  : default = {'brand': ' Not A;Brand', 'version': '99.0.0.0'}
    else            : default = {'brand': ' Not A;Brand', 'version': '99'}

    # Make brand list
    brandList = [default, {'brand': name, 'version': version}]

    # Convert to string
    return _makeBrandString(brandList)


def _makeBrandString(
    brandList: list # List of dicts {brand, version}
    ) -> str:
    """ Generates a string from the brand list of the user"""

    serial = []
    for d in brandList:
        
        brand   = d['brand']
        version = d['version']
        serial.append(f'"{brand}";v="{version}"')
    
    return ', '.join(serial)
